### PR TITLE
Need to get your updates

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
getting caught up on your work :)

**Comment by ghost** [comment]
So the script will detect if a directory already exists, if so it'll remove it. then create new directory. Else just create the directory

**Comment by ghost** [comment]
Made changes as mentioned in e-mail to Hugh. Easy to modify if we want to go back. Also added making the *.md file and adding header prepended. Ready for TECkit command. will wait until you're ready.

**Comment by HughP** [comment]
Ok Reading email. Been working on csv commands.

**Pull request merged**
