### PR TITLE
Work done in TMP_2 and TMP_3 folders

### PR DESCRIPTION
**Pull request by ghost**
- TMP_2 has the code to make tables
- TMP_3 is a collection of Bash script examples. A cookbook basically for reference.

### CODE REVIEW

**Comment by ghost** [comment]
- holding out on making any more changes to awesome-script.bash
- Moving the variables to global-vars.bash allows us to include them into the clean-up.bash script.

**Comment by ghost** [comment]
Yes! It works great for making temporary scripts that test little chunks of code. All you have to do is:
- source global-vars.bash

**Comment by ghost** [comment]
Hey you had mentioned making my comments better so I adopted a hybrid of your suggestions and MSG-XXX tags. The look like:

```
### (MSG-001) HUGH: It will look something like this in the code:
###
###
```

We can easily reference these changes. Kind of like shared bookmarks. :)

**Comment by ghost** [comment]
For me it runs to BREAKPOINT without error.

**Comment by ghost** [comment]
(MSG-001-B) HUGH: We can use global functions like this:

(MSG-001-C) HUGH: the function can be called and used just like echo except the function does all the work. Much cleaner when reading the script.

Just an idea and not applied to the whole awesome-script.bash

If you like it we can take common things. Like searching for files or build more intelligent commands while simplifying awesome-script.bash

e.g.:
move $THIS_FOLDER $THAT_FOLDER
move this-file.txt that-file.txt

**Comment by ghost** [comment]
Worked on it some more:

(MSG-003-B) HUGH: This is an example of Bash functions in action with SafeMove.

(MSG-006) HUGH: The above statements sounds good to me too.

(MSG-007) HUGH: I was not sure if the paragraph of commented out lines below are already run above in the James section? If so, then we should remove it.

(MSG-008) HUGH: The displaying of the table is handed off to a function called DisplayTable. Does not fully work at the moment.

**Comment by ghost** [comment]
Moved all TMP_\* folders to TMP_JD

**Comment by ghost** [comment]
(MSG-009) HUGH: This is a little misleading by putting an append. The file is deleted above if it exists every time the script runs. We should change >> to > So it's clear what we're doing at this point in the code.

(MSG-010) HUGH: This is a little misleading by putting an append. The file is deleted above if it exists every time the script runs. We should change >> to > So it's clear what we're doing at this point in the code.

(MSG-011) HUGH: in the array below "reset_file_array" the last variable KEYBOARDS_LANGUAGES needs a dollar sign. Issue Fixed, just an FYI message.

**Comment by HughP** [comment]
The reason for the append is that we actually re create the file with the `touch` command when we delete the file in the initial portion of the script. This means the file already exists. In that context append is the correct action to take?... does the command make more sense in that context?

**Pull request merged**
