### PR TITLE
new all BASH match-wiki-to-tab.bash script

### PR DESCRIPTION
**Pull request by ghost**
- I created a new match-wiki-to-tab.bash file that uses only BASH commands.
- I've switched to using https://atom.io/

Atom decided to go though awesome-script.bash and remove trailing white-space. Not an intentional edit.

### CODE REVIEW

**Comment by HughP** [comment]
This is awesome:  I discovered that for some reason the reason you did not see the code below was that it was never committed to the Repo... here is the CSVfix code for parsing the .tab file.

```
#This is read as:
#   Read the tab file, keep columns 1,4,7; then remove rows 2 if the length of the field is 0.

csvfix read_DSV -s '\t' -f 1,4,7 iso-639-3_20150505.tab | csvfix remove -f 2 -l 0 time.csv

# Read this for getting the first two letters of the file name:
# http://stackoverflow.com/questions/428109/extract-substring-in-bash
```

The above code will output a list of ISO 639-1 and 639-3 codes which refer to the same language.
If there is no ISO 639-1 code then the row is dropped.

**Comment by ghost** [comment]
cool. very nice.

**Comment by HughP** [comment]
Does that shorten the code base needed in your commit?

**Comment by ghost** [comment]
This is what I currently have:

```
# Generate a combined and complete master TAB file:
for I in $(find * -maxdepth 0 -iname 'iso-639-3*.tab'); do
    cat $I >> tmp_buffer.data
    echo >> tmp_buffer.data
done

# Create a new TAB with the only needed columbs:
csvfix read_dsv -s '\t' tmp_buffer.data | csvfix order -f 1,4 > tmp_buffer_csv_col14.data
```

The for loop finds all iso-639-3 tab files and creates on master tab file.
Then gets filtered to a csv with two columns.
Further down in the script we eliminate any three letter rows if they don't have a corresponding two letter. That elimination was what the c++ cleancsv.cpp file did.
It took a couple days for my brain to convert c++ to bash.
But in the end it is very similar to what you have.

**Comment by HughP** [comment]
Based on my first command 

`csvfix read_DSV -s '\t' -f 1,4,7 iso-639-3_20150505.tab` 

I think all of `csvfix read_dsv -s '\t' tmp_buffer.data | csvfix order -f 1,4 > tmp_buffer_csv_col14.data` can be reduced to one command and we would not need the pip. Is there any other reason to write to `temp_buffer.data` rather than directly to `tmp_buffer_csv_col14.data`?

**Comment by ghost** [comment]
tmp_buffer.data only contains the raw master tab list.
It could be renamed differently if you want to keep that data?
I wasn't sure so I added the step in for your convenience.

The cleaned up ( matching AAA to AA) version is saved to combined-iso-639-3.data
All files created by the script can be removed at the end. It's up to you.

**Comment by ghost** [comment]
q. Is there any other reason to write to temp_buffer.data rather than directly to tmp_buffer_csv_col14.data?
a. no

**Comment by HughP** [comment]
Yes. I have been doing the practice of removing temp files after they are called.

The only reason to keep the tem_buffer.data file is if we need the data again in another part of the script... is this the case? - it might be the case.... I have one cace I can think of but we need to talk about it face to face. Otherwise, I don't think there is any reason to keep the temp_buffer.

**Comment by ghost** [comment]
Sounds good

**Comment by HughP** [comment]
What about tonight after 7PM

**Comment by ghost** [comment]
- So unimatrixdoc/master was just merged with hughp/master.
- match-wiki-to-tab.bash was almost completely redone with new cool code.

**Pull request merged**
