### PR TITLE
Merge pull request #3 from HughP/master

### PR DESCRIPTION
**Pull request by HughP**
@unimatrixdoc  Hey I added some notes in the file. Look at @Jonathan in the inline comments.

### CODE REVIEW

**Comment by ghost** [comment]
Awesome. Will do.

**Comment by ghost** [comment]
alright, combined your .gitignore with my .gitignore
should be good for you to auto merge...

**Comment by ghost** [comment]
Still getting use to Github:

So, it says "HughP  wants to merge 4 commits into HughP:master" is that something i have to approve?

**Comment by HughP** [comment]
I merged it all into my public repo.

**Pull request merged**
